name: .NET Core

on: [push]

jobs:
  test:
    name: Debug Build & Test

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XML_DOC_MODE: skip
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet-version: [ 3.1 ]
        include:
          - dotnet-version: 2.1
            dotnet-sdk-version: 2.1.607
          - dotnet-version: 2.2
            dotnet-sdk-version: 2.2.207
          - dotnet-version: 3.0
            dotnet-sdk-version: 3.0.101
          - dotnet-version: 3.1
            dotnet-sdk-version: 3.1.101

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/cache@v1
      #   with:
      #     path: ${{ github.workspace }}/.nuget/packages
      #     key: 
      - name: Setup .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-sdk-version }}
      - name: Resotre Tool
        run: dotnet tool restore
      # - name: Lint
      #   run: dotnet format --check --dry-run
      - name: Debug Build
        run: dotnet build -c Debug
      - name: Test
        run: dotnet test -c Debug --no-build
